export const enum QueuesEnum {
    ACCOUNTS = 'ACCOUNTS',
    BALANCES = 'BALANCES',
    COLLECTIONS = 'COLLECTIONS',
    LISTINGS = 'LISTINGS',
    METADATA = 'METADATA',
    TOKENS = 'TOKENS',
    TRAITS = 'TRAITS',
    VALIDATORS = 'VALIDATORS',
}

export const enum JobsEnum {
    COMPUTE_COLLECTIONS = 'COMPUTE_COLLECTIONS',
    COMPUTE_METADATA = 'COMPUTE_METADATA',
    COMPUTE_RARITY = 'COMPUTE_RARITY',
    COMPUTE_STATS = 'COMPUTE_STATS',
    COMPUTE_TRAITS = 'COMPUTE_TRAITS',
    DELETE_TRAITS = 'DELETE_TRAITS',
    FETCH_ACCOUNTS = 'FETCH_ACCOUNTS',
    FETCH_BALANCES = 'FETCH_BALANCES',
    FETCH_COLLECTIONS = 'FETCH_COLLECTIONS',
    FETCH_EXTRA = 'FETCH_EXTRA',
    FETCH_OFFERS = 'FETCH_OFFERS',
    INVALIDATE_LISTINGS = 'INVALIDATE_LISTINGS',
    SYNC_COLLECTION_TRANSFER = 'SYNC_COLLECTION_TRANSFER',
}
