export * from '~/pallet/identity/calls/types/add-sub'
export * from '~/pallet/identity/calls/types/provide-judgement'
export * from '~/pallet/identity/calls/types/rename-sub'
export * from '~/pallet/identity/calls/types/set-identity'
export * from '~/pallet/identity/calls/types/set-subs'
