'use strict'
Object.defineProperty(exports, '__esModule', { value: true })
exports.paras =
    exports.paraInherent =
    exports.configuration =
    exports.stakeExchange =
    exports.nominationPools =
    exports.voterList =
    exports.imOnline =
    exports.treasury =
    exports.grandpa =
    exports.staking =
    exports.electionProviderMultiPhase =
    exports.babe =
    exports.efinityUtility =
    exports.efinityXcm =
    exports.sudo =
    exports.migrations =
    exports.proxy =
    exports.messageQueue =
    exports.safeMode =
    exports.identity =
    exports.claims =
    exports.multiTokensMigration =
    exports.matrixUtility =
    exports.extrinsicPause =
    exports.marketplace =
    exports.fuelTanks =
    exports.pools =
    exports.multiTokens =
    exports.bounties =
    exports.xTokens =
    exports.matrixXcm =
    exports.ormlXcm =
    exports.dmpQueue =
    exports.polkadotXcm =
    exports.xcmpQueue =
    exports.session =
    exports.collatorStaking =
    exports.multisig =
    exports.technicalMembership =
    exports.communityPool =
    exports.technicalCommittee =
    exports.council =
    exports.democracy =
    exports.balances =
    exports.utility =
    exports.scheduler =
    exports.preimage =
    exports.timestamp =
    exports.parachainSystem =
    exports.system =
        void 0
exports.voteManager =
    exports.fellowshipReferenda =
    exports.fellowshipCollective =
    exports.whitelist =
    exports.referenda =
    exports.convictionVoting =
    exports.beefy =
    exports.validatorManager =
    exports.assignedSlots =
    exports.parasSudoWrapper =
    exports.xcmPallet =
    exports.crowdloan =
    exports.auctions =
    exports.slots =
    exports.registrar =
    exports.parasSlashing =
    exports.parasDisputes =
    exports.hrmp =
    exports.ump =
    exports.initializer =
        void 0
exports.system = require('./system/calls')
exports.parachainSystem = require('./parachain-system/calls')
exports.timestamp = require('./timestamp/calls')
exports.preimage = require('./preimage/calls')
exports.scheduler = require('./scheduler/calls')
exports.utility = require('./utility/calls')
exports.balances = require('./balances/calls')
exports.democracy = require('./democracy/calls')
exports.council = require('./council/calls')
exports.technicalCommittee = require('./technical-committee/calls')
exports.communityPool = require('./community-pool/calls')
exports.technicalMembership = require('./technical-membership/calls')
exports.multisig = require('./multisig/calls')
exports.collatorStaking = require('./collator-staking/calls')
exports.session = require('./session/calls')
exports.xcmpQueue = require('./xcmp-queue/calls')
exports.polkadotXcm = require('./polkadot-xcm/calls')
exports.dmpQueue = require('./dmp-queue/calls')
exports.ormlXcm = require('./orml-xcm/calls')
exports.matrixXcm = require('./matrix-xcm/calls')
exports.xTokens = require('./x-tokens/calls')
exports.bounties = require('./bounties/calls')
exports.multiTokens = require('./multi-tokens/calls')
exports.pools = require('./pools/calls')
exports.fuelTanks = require('./fuel-tanks/calls')
exports.marketplace = require('./marketplace/calls')
exports.extrinsicPause = require('./extrinsic-pause/calls')
exports.matrixUtility = require('./matrix-utility/calls')
exports.multiTokensMigration = require('./multi-tokens-migration/calls')
exports.claims = require('./claims/calls')
exports.identity = require('./identity/calls')
exports.safeMode = require('./safe-mode/calls')
exports.messageQueue = require('./message-queue/calls')
exports.proxy = require('./proxy/calls')
exports.migrations = require('./migrations/calls')
exports.sudo = require('./sudo/calls')
exports.efinityXcm = require('./efinity-xcm/calls')
exports.efinityUtility = require('./efinity-utility/calls')
exports.babe = require('./babe/calls')
exports.electionProviderMultiPhase = require('./election-provider-multi-phase/calls')
exports.staking = require('./staking/calls')
exports.grandpa = require('./grandpa/calls')
exports.treasury = require('./treasury/calls')
exports.imOnline = require('./im-online/calls')
exports.voterList = require('./voter-list/calls')
exports.nominationPools = require('./nomination-pools/calls')
exports.stakeExchange = require('./stake-exchange/calls')
exports.configuration = require('./configuration/calls')
exports.paraInherent = require('./para-inherent/calls')
exports.paras = require('./paras/calls')
exports.initializer = require('./initializer/calls')
exports.ump = require('./ump/calls')
exports.hrmp = require('./hrmp/calls')
exports.parasDisputes = require('./paras-disputes/calls')
exports.parasSlashing = require('./paras-slashing/calls')
exports.registrar = require('./registrar/calls')
exports.slots = require('./slots/calls')
exports.auctions = require('./auctions/calls')
exports.crowdloan = require('./crowdloan/calls')
exports.xcmPallet = require('./xcm-pallet/calls')
exports.parasSudoWrapper = require('./paras-sudo-wrapper/calls')
exports.assignedSlots = require('./assigned-slots/calls')
exports.validatorManager = require('./validator-manager/calls')
exports.beefy = require('./beefy/calls')
exports.convictionVoting = require('./conviction-voting/calls')
exports.referenda = require('./referenda/calls')
exports.whitelist = require('./whitelist/calls')
exports.fellowshipCollective = require('./fellowship-collective/calls')
exports.fellowshipReferenda = require('./fellowship-referenda/calls')
exports.voteManager = require('./vote-manager/calls')
