'use strict'
Object.defineProperty(exports, '__esModule', { value: true })
exports.paraInclusion =
    exports.stakeExchange =
    exports.nominationPools =
    exports.voterList =
    exports.imOnline =
    exports.treasury =
    exports.grandpa =
    exports.staking =
    exports.electionProviderMultiPhase =
    exports.offences =
    exports.efinityUtility =
    exports.efinityXcm =
    exports.sudo =
    exports.migrations =
    exports.proxy =
    exports.messageQueue =
    exports.safeMode =
    exports.identity =
    exports.claims =
    exports.multiTokensMigration =
    exports.matrixUtility =
    exports.extrinsicPause =
    exports.marketplace =
    exports.fuelTanks =
    exports.pools =
    exports.multiTokens =
    exports.bounties =
    exports.xTokens =
    exports.unknownTokens =
    exports.matrixXcm =
    exports.ormlXcm =
    exports.dmpQueue =
    exports.cumulusXcm =
    exports.polkadotXcm =
    exports.xcmpQueue =
    exports.session =
    exports.collatorStaking =
    exports.multisig =
    exports.technicalMembership =
    exports.communityPool =
    exports.technicalCommittee =
    exports.council =
    exports.democracy =
    exports.transactionPayment =
    exports.balances =
    exports.utility =
    exports.scheduler =
    exports.preimage =
    exports.parachainSystem =
    exports.system =
        void 0
exports.voteManager =
    exports.fellowshipReferenda =
    exports.fellowshipCollective =
    exports.whitelist =
    exports.referenda =
    exports.convictionVoting =
    exports.validatorManager =
    exports.assignedSlots =
    exports.xcmPallet =
    exports.crowdloan =
    exports.auctions =
    exports.slots =
    exports.registrar =
    exports.parasDisputes =
    exports.hrmp =
    exports.ump =
    exports.paras =
        void 0
exports.system = require('./system/events')
exports.parachainSystem = require('./parachain-system/events')
exports.preimage = require('./preimage/events')
exports.scheduler = require('./scheduler/events')
exports.utility = require('./utility/events')
exports.balances = require('./balances/events')
exports.transactionPayment = require('./transaction-payment/events')
exports.democracy = require('./democracy/events')
exports.council = require('./council/events')
exports.technicalCommittee = require('./technical-committee/events')
exports.communityPool = require('./community-pool/events')
exports.technicalMembership = require('./technical-membership/events')
exports.multisig = require('./multisig/events')
exports.collatorStaking = require('./collator-staking/events')
exports.session = require('./session/events')
exports.xcmpQueue = require('./xcmp-queue/events')
exports.polkadotXcm = require('./polkadot-xcm/events')
exports.cumulusXcm = require('./cumulus-xcm/events')
exports.dmpQueue = require('./dmp-queue/events')
exports.ormlXcm = require('./orml-xcm/events')
exports.matrixXcm = require('./matrix-xcm/events')
exports.unknownTokens = require('./unknown-tokens/events')
exports.xTokens = require('./x-tokens/events')
exports.bounties = require('./bounties/events')
exports.multiTokens = require('./multi-tokens/events')
exports.pools = require('./pools/events')
exports.fuelTanks = require('./fuel-tanks/events')
exports.marketplace = require('./marketplace/events')
exports.extrinsicPause = require('./extrinsic-pause/events')
exports.matrixUtility = require('./matrix-utility/events')
exports.multiTokensMigration = require('./multi-tokens-migration/events')
exports.claims = require('./claims/events')
exports.identity = require('./identity/events')
exports.safeMode = require('./safe-mode/events')
exports.messageQueue = require('./message-queue/events')
exports.proxy = require('./proxy/events')
exports.migrations = require('./migrations/events')
exports.sudo = require('./sudo/events')
exports.efinityXcm = require('./efinity-xcm/events')
exports.efinityUtility = require('./efinity-utility/events')
exports.offences = require('./offences/events')
exports.electionProviderMultiPhase = require('./election-provider-multi-phase/events')
exports.staking = require('./staking/events')
exports.grandpa = require('./grandpa/events')
exports.treasury = require('./treasury/events')
exports.imOnline = require('./im-online/events')
exports.voterList = require('./voter-list/events')
exports.nominationPools = require('./nomination-pools/events')
exports.stakeExchange = require('./stake-exchange/events')
exports.paraInclusion = require('./para-inclusion/events')
exports.paras = require('./paras/events')
exports.ump = require('./ump/events')
exports.hrmp = require('./hrmp/events')
exports.parasDisputes = require('./paras-disputes/events')
exports.registrar = require('./registrar/events')
exports.slots = require('./slots/events')
exports.auctions = require('./auctions/events')
exports.crowdloan = require('./crowdloan/events')
exports.xcmPallet = require('./xcm-pallet/events')
exports.assignedSlots = require('./assigned-slots/events')
exports.validatorManager = require('./validator-manager/events')
exports.convictionVoting = require('./conviction-voting/events')
exports.referenda = require('./referenda/events')
exports.whitelist = require('./whitelist/events')
exports.fellowshipCollective = require('./fellowship-collective/events')
exports.fellowshipReferenda = require('./fellowship-referenda/events')
exports.voteManager = require('./vote-manager/events')
