'use strict'
Object.defineProperty(exports, '__esModule', { value: true })
exports.configuration =
    exports.stakeExchange =
    exports.nominationPools =
    exports.voterList =
    exports.imOnline =
    exports.treasury =
    exports.grandpa =
    exports.staking =
    exports.electionProviderMultiPhase =
    exports.offences =
    exports.babe =
    exports.randomnessCollectiveFlip =
    exports.efinityXcm =
    exports.sudo =
    exports.migrations =
    exports.proxy =
    exports.messageQueue =
    exports.unknownTokens =
    exports.auraExt =
    exports.aura =
    exports.safeMode =
    exports.identity =
    exports.claims =
    exports.extrinsicPause =
    exports.marketplace =
    exports.fuelTanks =
    exports.pools =
    exports.multiTokens =
    exports.bounties =
    exports.matrixXcm =
    exports.dmpQueue =
    exports.polkadotXcm =
    exports.xcmpQueue =
    exports.session =
    exports.collatorStaking =
    exports.authorship =
    exports.multisig =
    exports.technicalMembership =
    exports.communityPool =
    exports.technicalCommittee =
    exports.council =
    exports.democracy =
    exports.transactionPayment =
    exports.balances =
    exports.scheduler =
    exports.preimage =
    exports.parachainInfo =
    exports.timestamp =
    exports.parachainSystem =
    exports.system =
        void 0
exports.authorityDiscovery =
    exports.historical =
    exports.voteManager =
    exports.fellowshipReferenda =
    exports.fellowshipCollective =
    exports.whitelist =
    exports.referenda =
    exports.convictionVoting =
    exports.mmrLeaf =
    exports.mmr =
    exports.beefy =
    exports.validatorManager =
    exports.assignedSlots =
    exports.xcmPallet =
    exports.crowdloan =
    exports.auctions =
    exports.slots =
    exports.registrar =
    exports.parasSlashing =
    exports.parasDisputes =
    exports.paraSessionInfo =
    exports.hrmp =
    exports.ump =
    exports.dmp =
    exports.initializer =
    exports.paras =
    exports.paraScheduler =
    exports.paraInherent =
    exports.paraInclusion =
    exports.parasShared =
        void 0
exports.system = require('./system/storage')
exports.parachainSystem = require('./parachain-system/storage')
exports.timestamp = require('./timestamp/storage')
exports.parachainInfo = require('./parachain-info/storage')
exports.preimage = require('./preimage/storage')
exports.scheduler = require('./scheduler/storage')
exports.balances = require('./balances/storage')
exports.transactionPayment = require('./transaction-payment/storage')
exports.democracy = require('./democracy/storage')
exports.council = require('./council/storage')
exports.technicalCommittee = require('./technical-committee/storage')
exports.communityPool = require('./community-pool/storage')
exports.technicalMembership = require('./technical-membership/storage')
exports.multisig = require('./multisig/storage')
exports.authorship = require('./authorship/storage')
exports.collatorStaking = require('./collator-staking/storage')
exports.session = require('./session/storage')
exports.xcmpQueue = require('./xcmp-queue/storage')
exports.polkadotXcm = require('./polkadot-xcm/storage')
exports.dmpQueue = require('./dmp-queue/storage')
exports.matrixXcm = require('./matrix-xcm/storage')
exports.bounties = require('./bounties/storage')
exports.multiTokens = require('./multi-tokens/storage')
exports.pools = require('./pools/storage')
exports.fuelTanks = require('./fuel-tanks/storage')
exports.marketplace = require('./marketplace/storage')
exports.extrinsicPause = require('./extrinsic-pause/storage')
exports.claims = require('./claims/storage')
exports.identity = require('./identity/storage')
exports.safeMode = require('./safe-mode/storage')
exports.aura = require('./aura/storage')
exports.auraExt = require('./aura-ext/storage')
exports.unknownTokens = require('./unknown-tokens/storage')
exports.messageQueue = require('./message-queue/storage')
exports.proxy = require('./proxy/storage')
exports.migrations = require('./migrations/storage')
exports.sudo = require('./sudo/storage')
exports.efinityXcm = require('./efinity-xcm/storage')
exports.randomnessCollectiveFlip = require('./randomness-collective-flip/storage')
exports.babe = require('./babe/storage')
exports.offences = require('./offences/storage')
exports.electionProviderMultiPhase = require('./election-provider-multi-phase/storage')
exports.staking = require('./staking/storage')
exports.grandpa = require('./grandpa/storage')
exports.treasury = require('./treasury/storage')
exports.imOnline = require('./im-online/storage')
exports.voterList = require('./voter-list/storage')
exports.nominationPools = require('./nomination-pools/storage')
exports.stakeExchange = require('./stake-exchange/storage')
exports.configuration = require('./configuration/storage')
exports.parasShared = require('./paras-shared/storage')
exports.paraInclusion = require('./para-inclusion/storage')
exports.paraInherent = require('./para-inherent/storage')
exports.paraScheduler = require('./para-scheduler/storage')
exports.paras = require('./paras/storage')
exports.initializer = require('./initializer/storage')
exports.dmp = require('./dmp/storage')
exports.ump = require('./ump/storage')
exports.hrmp = require('./hrmp/storage')
exports.paraSessionInfo = require('./para-session-info/storage')
exports.parasDisputes = require('./paras-disputes/storage')
exports.parasSlashing = require('./paras-slashing/storage')
exports.registrar = require('./registrar/storage')
exports.slots = require('./slots/storage')
exports.auctions = require('./auctions/storage')
exports.crowdloan = require('./crowdloan/storage')
exports.xcmPallet = require('./xcm-pallet/storage')
exports.assignedSlots = require('./assigned-slots/storage')
exports.validatorManager = require('./validator-manager/storage')
exports.beefy = require('./beefy/storage')
exports.mmr = require('./mmr/storage')
exports.mmrLeaf = require('./mmr-leaf/storage')
exports.convictionVoting = require('./conviction-voting/storage')
exports.referenda = require('./referenda/storage')
exports.whitelist = require('./whitelist/storage')
exports.fellowshipCollective = require('./fellowship-collective/storage')
exports.fellowshipReferenda = require('./fellowship-referenda/storage')
exports.voteManager = require('./vote-manager/storage')
exports.historical = require('./historical/storage')
exports.authorityDiscovery = require('./authority-discovery/storage')
