export * from '~/pallet/multi-tokens/calls/create-collection'
export * from '~/pallet/multi-tokens/calls/mint'
export * from '~/pallet/multi-tokens/calls/batch-mint'
export * from '~/pallet/multi-tokens/calls/force-create-collection'
export * from '~/pallet/multi-tokens/calls/force-create-ethereum-collection'
export * from '~/pallet/multi-tokens/calls/force-mint'
export * from '~/pallet/multi-tokens/calls/types'
