export * from '~/pallet/identity/calls/add-sub'
export * from '~/pallet/identity/calls/rename-sub'
export * from '~/pallet/identity/calls/set-subs'
export * from '~/pallet/identity/calls/provide-judgement'
export * from '~/pallet/identity/calls/set-identity'
export * from '~/pallet/identity/calls/types'
