import { buildTransferAllBalanceView, buildTransferBalanceView } from './builders/balances'
import { buildGenericView } from './builders/generic'
import {
    buildAcceptCollectionTransferView,
    buildAddTokenToGroupView,
    buildApproveCollectionView,
    buildApproveTokenView,
    buildBatchMintTokenView,
    buildBatchInfuseTokenView,
    buildBatchSetAttributeView,
    buildBatchTransferTokenView,
    buildBurnTokenView,
    buildCreateCollectionView,
    buildCreateTokenGroupView,
    buildDestroyCollectionView,
    buildDestroyTokenGroupView,
    buildFreezeView,
    buildInfuseTokenView,
    buildMintTokenView,
    buildMutateCollectionView,
    buildMutateTokenView,
    buildRemoveAllAttributesView,
    buildRemoveAttributeView,
    buildRemoveTokenFromGroupView,
    buildRemoveTokenGroupAttributeView,
    buildSetAttributeView,
    buildSetTokenGroupAttributeView,
    buildSetTokenGroupsView,
    buildSetRoyaltyView,
    buildThawView,
    buildTransferTokenView,
    buildUnapproveCollectionView,
    buildUnapproveTokenView,
    buildCancelCollectionTransferView,
} from './builders/multitokens'
import {
    buildAddWhitelistedAccountsView,
    buildAnswerCounterOfferView,
    buildCancelListingView,
    buildCreateListingView,
    buildCreateListingAndMatchView,
    buildFillListingView,
    buildFinalizeAuctionView,
    buildPlaceBidView,
    buildPlaceCounterOfferView,
    buildRemoveWhitelistedAccountsView,
    buildSetProtocolFeeView,
} from './builders/marketplace'
import {
    buildAddFuelTankAccountView,
    buildBatchAddFuelTankAccountView,
    buildBatchRemoveFuelTankAccountView,
    buildCreateFuelTankView,
    buildDestroyFuelTankView,
    buildInsertFuelTankRuleSetView,
    buildMutateFuelTankFreezeStateView,
    buildMutateFuelTankView,
    buildRemoveFuelTankAccountRuleDataView,
    buildRemoveFuelTankAccountView,
    buildRemoveExpiredFuelTankAccountView,
    buildRemoveFuelTankRuleSetView,
    buildSetFuelTankConsumptionView,
} from './builders/fuel-tanks'
import {
    buildBondView,
    buildCreatePoolView,
    buildDestroyPoolView,
    buildMutatePoolView,
    buildNominatePoolView,
    buildUnbondView,
    buildWithdrawUnbondedView,
} from './builders/nomination-pools'
import { buildBuyOfferView, buildCancelOfferView, buildCreateOfferView } from './builders/stake-exchange'
import { buildBatchView, buildForceBatchView, buildMatrixBatchView } from './builders/utility'
import { buildTeleportView } from './builders/xcm'
import type { CallParts, ViewBuilderFn } from './types'

const CALL_BUILDERS: Record<string, ViewBuilderFn> = {
    'Balances::transfer_keep_alive': buildTransferBalanceView,
    'Balances::transfer_allow_death': buildTransferBalanceView,
    'Balances::transfer_all': buildTransferAllBalanceView,
    'XcmPallet::limited_teleport_assets': buildTeleportView,
    'PolkadotXcm::limited_teleport_assets': buildTeleportView,
    'MultiTokens::transfer': buildTransferTokenView,
    'MultiTokens::batch_mint': buildBatchMintTokenView,
    'MultiTokens::batch_set_attribute': buildBatchSetAttributeView,
    'MultiTokens::batch_transfer': buildBatchTransferTokenView,
    'MultiTokens::burn': buildBurnTokenView,
    'MultiTokens::mint': buildMintTokenView,
    'MultiTokens::infuse': buildInfuseTokenView,
    'MultiTokens::batch_infuse': buildBatchInfuseTokenView,
    'MultiTokens::set_attribute': buildSetAttributeView,
    'MultiTokens::create_collection': buildCreateCollectionView,
    'MultiTokens::approve_collection': buildApproveCollectionView,
    'MultiTokens::accept_collection_transfer': buildAcceptCollectionTransferView,
    'MultiTokens::cancel_collection_transfer': buildCancelCollectionTransferView,
    'MultiTokens::create_token_group': buildCreateTokenGroupView,
    'MultiTokens::destroy_token_group': buildDestroyTokenGroupView,
    'MultiTokens::add_token_to_group': buildAddTokenToGroupView,
    'MultiTokens::remove_token_from_group': buildRemoveTokenFromGroupView,
    'MultiTokens::set_token_groups': buildSetTokenGroupsView,
    'MultiTokens::set_token_group_attribute': buildSetTokenGroupAttributeView,
    'MultiTokens::remove_token_group_attribute': buildRemoveTokenGroupAttributeView,
    'MultiTokens::approve_token': buildApproveTokenView,
    'MultiTokens::destroy_collection': buildDestroyCollectionView,
    'MultiTokens::freeze': buildFreezeView,
    'MultiTokens::mutate_collection': buildMutateCollectionView,
    'MultiTokens::mutate_token': buildMutateTokenView,
    'MultiTokens::remove_all_attributes': buildRemoveAllAttributesView,
    'MultiTokens::remove_attribute': buildRemoveAttributeView,
    'MultiTokens::set_royalty': buildSetRoyaltyView,
    'MultiTokens::thaw': buildThawView,
    'MultiTokens::unapprove_collection': buildUnapproveCollectionView,
    'MultiTokens::unapprove_token': buildUnapproveTokenView,
    'Marketplace::create_listing': buildCreateListingView,
    'Marketplace::create_listing_and_match': buildCreateListingAndMatchView,
    'Marketplace::fill_listing': buildFillListingView,
    'Marketplace::cancel_listing': buildCancelListingView,
    'Marketplace::finalize_auction': buildFinalizeAuctionView,
    'Marketplace::place_bid': buildPlaceBidView,
    'Marketplace::add_whitelisted_accounts': buildAddWhitelistedAccountsView,
    'Marketplace::remove_whitelisted_accounts': buildRemoveWhitelistedAccountsView,
    'Marketplace::place_counter_offer': buildPlaceCounterOfferView,
    'Marketplace::answer_counter_offer': buildAnswerCounterOfferView,
    'Marketplace::set_protocol_fee': buildSetProtocolFeeView,
    'FuelTanks::add_account': buildAddFuelTankAccountView,
    'FuelTanks::batch_add_account': buildBatchAddFuelTankAccountView,
    'FuelTanks::batch_remove_account': buildBatchRemoveFuelTankAccountView,
    'FuelTanks::create_fuel_tank': buildCreateFuelTankView,
    'FuelTanks::destroy_fuel_tank': buildDestroyFuelTankView,
    'FuelTanks::force_set_consumption': buildSetFuelTankConsumptionView,
    'FuelTanks::insert_rule_set': buildInsertFuelTankRuleSetView,
    'FuelTanks::mutate_freeze_state': buildMutateFuelTankFreezeStateView,
    'FuelTanks::mutate_fuel_tank': buildMutateFuelTankView,
    'FuelTanks::remove_account': buildRemoveFuelTankAccountView,
    'FuelTanks::remove_account_rule_data': buildRemoveFuelTankAccountRuleDataView,
    'FuelTanks::remove_rule_set': buildRemoveFuelTankRuleSetView,
    'FuelTanks::remove_expired_account': buildRemoveExpiredFuelTankAccountView,
    'NominationPools::create': buildCreatePoolView,
    'NominationPools::bond': buildBondView,
    'NominationPools::unbond': buildUnbondView,
    'NominationPools::withdraw_unbonded': buildWithdrawUnbondedView,
    'NominationPools::nominate': buildNominatePoolView,
    'NominationPools::mutate': buildMutatePoolView,
    'NominationPools::destroy': buildDestroyPoolView,
    'StakeExchange::create_offer': buildCreateOfferView,
    'StakeExchange::cancel_offer': buildCancelOfferView,
    'StakeExchange::buy': buildBuyOfferView,
    'MatrixUtility::batch': buildMatrixBatchView,
    'MatrixUtility::batch_all': buildBatchView,
    'Utility::batch': buildBatchView,
    'Utility::batch_all': buildBatchView,
    'Utility::force_batch': buildForceBatchView,
}

export function getBuilderForCall(call: CallParts): ViewBuilderFn {
    const callId = `${call.pallet}::${call.method}`
    return CALL_BUILDERS[callId] ?? buildGenericView
}
