name: Auto Assign
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    name: Assignees & Reviewers
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: leonardocustodio, zlayine

