name: ESLint
on:
  push:

jobs:
  lint:
    name: Code Lint & Format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest
        run_install: false

    - name: Install Node 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install packages
      run: |
        pnpm add -g eslint prettier
        pnpm install

    - name: Run ESLint
      run: pnpm run ci:lint

    - name: Run Prettier
      run: pnpm run ci:prettier
