name: ESLint
on:
  push:

jobs:
  lint:
    name: Code Standard & Format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Install Node 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install packages
      run: pnpm install

    - name: Run ESLint
      run: pnpm exec eslint .
