name: ESLint
on:
  push:
    branches:
      - master
  pull_request:

jobs:

  tests:

    name: Code Standard & Format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Node v20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install modules
      run: npm ci

    - name: Run ESLint
      run: npm run lint
