name: ESLint
on:
  push:

jobs:
  lint:
    name: Code Standard & Format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node v20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install packages
      run: pnpm install

    - name: Run ESLint
      run: pnpm exec eslint .
