name: Link Checker
on:
  push:

# Declare default permissions as read only.
permissions: read-all

jobs:
  check:
    name: Markdown link checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
